// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1579260194);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1579260314);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1439);
user_pref("browser.cache.disk.capacity", 153600);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1579260164);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{886f72ce-2471-46b6-89b7-b87ef01ab198}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon,google");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true,\"baseDomain\":\"amazon.com\"},{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1579260201310");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1579261991310");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1579260170880");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1579263770880");
user_pref("browser.search.region", "DE");
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1579260169");
user_pref("browser.slowStartup.averageTime", 3797);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "http://localhost/search");
user_pref("browser.startup.homepage_override.buildID", "20200107212959");
user_pref("browser.startup.homepage_override.mstone", "68.4.1");
user_pref("browser.startup.lastColdStartupCheck", 1579260166);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1579260168917");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "68.4.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.4.1");
user_pref("extensions.lastPlatformVersion", "68.4.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"5883d3a9-63e2-4f03-8545-3416c50becf8\",\"fxmonitor@mozilla.org\":\"6795acf4-1408-4edb-afbd-aac7de518403\",\"screenshots@mozilla.org\":\"269914e6-caf0-4317-b705-c77763326763\",\"webcompat-reporter@mozilla.org\":\"52030aff-174d-4a22-bd22-00f410657ae1\",\"webcompat@mozilla.org\":\"13ad12be-c5ff-4d64-96c1-01735833dc2a\",\"default-theme@mozilla.org\":\"07d3ae83-1797-4803-a8c3-fb8b867615da\",\"google@search.mozilla.org\":\"b97a37d7-c1b1-4c40-8035-e5a0b6ea2b0e\",\"amazondotcom@search.mozilla.org\":\"f572789c-f3fa-4039-b2ab-71e183a421f0\",\"bing@search.mozilla.org\":\"d7dfe17a-a22a-4eb5-85da-652544c425e9\",\"ddg@search.mozilla.org\":\"5f400d69-7aaa-4976-9372-c21e759ba294\",\"ebay@search.mozilla.org\":\"67758bd5-f80b-40b5-8dfd-c588549cea67\",\"twitter@search.mozilla.org\":\"c3f5a8a1-5727-479e-8b43-84341e78feef\",\"wikipedia@search.mozilla.org\":\"a595e5a6-2d03-42d6-be2f-e26c8b6fef93\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.privacy.disable_button.cookie_exceptions", false);
user_pref("privacy.history.custom", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("security.sandbox.content.tempDirSuffix", "d066b795-4136-4ed1-bde1-faca05081fe8");
user_pref("security.sandbox.plugin.tempDirSuffix", "1ba9a33d-122c-4d30-9b06-f0ac856349d9");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1579260162);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200107212959");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("capability.policy.localfilelinks.checkloaduri.enabled", "allAccess");
user_pref("capability.policy.localfilelinks.sites", "http://localhost");
user_pref("capability.policy.policynames", "localfilelinks");

